# Generated by Django 2.1.4 on 2018-12-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20181231_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_str', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.Menu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.User')),
            ],
            options={
                'db_table': 'UserPermis_Table',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(through='Models.User_Menu', to='Models.Menu'),
        ),
    ]
