# Generated by Django 2.1.4 on 2018-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_auto_20181231_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zgaccess_str',
            field=models.CharField(db_column='ZGaccess_str', max_length=20, null=True),
        ),
    ]
