# Generated by Django 2.1.4 on 2019-01-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_auto_20181231_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='maxchild',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
