# Generated by Django 2.1.4 on 2019-01-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_menu_maxchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DepartRole_Table',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('node', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(through='Models.Depart_Role', to='Models.Role')),
            ],
            options={
                'db_table': 'Department_Table',
            },
        ),
        migrations.AddField(
            model_name='depart_role',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.Department'),
        ),
        migrations.AddField(
            model_name='depart_role',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.Role'),
        ),
    ]
