# Generated by Django 2.1.4 on 2019-01-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_auto_20190104_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': False},
        ),
    ]
