# Generated by Django 2.1.4 on 2019-01-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_auto_20190104_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='users',
            new_name='roles',
        ),
        migrations.RemoveField(
            model_name='department',
            name='depart_id',
        ),
    ]
