# Generated by Django 2.1.4 on 2019-01-04 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_auto_20190104_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.Department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.User')),
            ],
            options={
                'db_table': 'DepartUser_Table',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(through='Models.Depart_User', to='Models.User'),
        ),
    ]
