# Generated by Django 2.1.4 on 2019-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_auto_20190113_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(db_column='goodsName', max_length=32)),
            ],
            options={
                'db_table': 'Goods_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('managername', models.CharField(db_column='managerName', max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Supplier_Table',
                'managed': False,
            },
        ),
    ]
