# Generated by Django 2.1.4 on 2019-01-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0015_goods_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('manager', models.CharField(db_column='managerName', max_length=15)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Manufactor_Table',
            },
        ),
    ]
