# Generated by Django 2.1.4 on 2019-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0016_manufactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodscat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.TextField(blank=True, db_column='catName', null=True)),
            ],
            options={
                'db_table': 'goodsCat_Table',
            },
        ),
        migrations.AlterModelOptions(
            name='manufactor',
            options={'managed': False},
        ),
    ]
