# Generated by Django 2.1.4 on 2019-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0017_auto_20190118_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('Sellername', models.CharField(db_column='SellerName', max_length=10)),
                ('Sellerphone', models.CharField(max_length=50)),
                ('Sellerproperty', models.CharField(max_length=64)),
                ('SellerOwner', models.CharField(max_length=64)),
                ('SellerOwnerPhone', models.CharField(max_length=64)),
                ('SellerOwnerLevel', models.CharField(max_length=64)),
                ('SellerOwnerNo', models.CharField(max_length=64)),
                ('SellerOwnerArea', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Seller_Table',
            },
        ),
    ]
