# Generated by Django 2.1.4 on 2019-01-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0019_auto_20190119_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
