# Generated by Django 2.1.4 on 2019-01-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0020_auto_20190119_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
