# Generated by Django 2.1.4 on 2019-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0021_auto_20190119_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
