# Generated by Django 2.1.4 on 2019-01-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0022_role_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPorprety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerpropertyType', models.CharField(db_column='SellerP_Str', max_length=10)),
            ],
            options={
                'db_table': 'SellerPorprety_Table',
            },
        ),
    ]
