# Generated by Django 2.1.4 on 2019-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0022_role_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPorprety',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('SellerpropertyType', models.CharField(db_column='SellerP_Str', max_length=10)),
                ('SellerpropertyID', models.AutoField(db_column='Inx', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SellerPorprety_Table',
            },
        ),
    ]
