# Generated by Django 2.1.4 on 2019-01-21 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0023_sellerporprety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advise', models.TextField(blank=True, null=True)),
                ('step', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Approval_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('node', models.IntegerField(blank=True, null=True)),
                ('prefunc', models.IntegerField(blank=True, null=True)),
                ('curfunc', models.IntegerField(blank=True, null=True)),
                ('afterfunc', models.IntegerField(blank=True, null=True)),
                ('value1', models.IntegerField(blank=True, null=True)),
                ('value2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Base_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Work_Table',
                'managed': False,
            },
        ),
    ]
