# Generated by Django 2.1.4 on 2019-01-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0026_auto_20190122_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='manufactor',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='seller',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.DeleteModel(
            name='StockOut',
        ),
    ]
