# Generated by Django 2.1.4 on 2019-01-22 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0027_auto_20190122_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockin_id', models.IntegerField(null=True)),
                ('goods_sn', models.CharField(db_column='goodsSn', max_length=100)),
                ('in_amount', models.IntegerField(blank=True, db_column='inAmount', null=True)),
                ('cost', models.FloatField(null=True)),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cat', models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsCat_in', to='Models.GoodsCat')),
                ('goods', models.ForeignKey(db_column='goodsId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_in', to='Models.Goods')),
                ('manufactor', models.ForeignKey(db_column='manufactorId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufactor_stockIn', to='Models.Manufactor')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stockIn', to='Models.User')),
                ('seller', models.ForeignKey(db_column='sellerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_stockIn', to='Models.Seller')),
                ('supplier', models.ForeignKey(db_column='supplierId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_stockIn', to='Models.Supplier')),
            ],
            options={
                'db_table': 'StockIn_Table',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockout_id', models.IntegerField(null=True)),
                ('goods_sn', models.CharField(db_column='goodsSn', max_length=100)),
                ('outamount', models.IntegerField(blank=True, db_column='outAmount', null=True)),
                ('price', models.FloatField(null=True)),
                ('out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_phone', models.CharField(db_column='KHPhone', max_length=100)),
                ('customer_name', models.CharField(db_column='KeHuName', max_length=50)),
                ('cat', models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsCat_out', to='Models.GoodsCat')),
                ('goods', models.ForeignKey(db_column='goodsId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_out', to='Models.Goods')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stockOut', to='Models.User')),
                ('seller', models.ForeignKey(db_column='sellerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_stockOut', to='Models.Seller')),
            ],
            options={
                'db_table': 'StockOut_Table',
            },
        ),
    ]
