# Generated by Django 2.1.4 on 2019-01-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0036_auto_20190127_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='videomeau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('firstlayer', models.IntegerField(default='0')),
                ('secondlayer', models.IntegerField(default='0')),
                ('thirdlayer', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'VideoMeau_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default='80')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=32)),
                ('rtsp_port', models.IntegerField(default='553')),
                ('stream_type', models.IntegerField(default='1')),
                ('device_port', models.IntegerField(default='8000')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.videomeau')),
            ],
            options={
                'db_table': 'Video_Table',
            },
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='cat',
            field=models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.GoodsCat'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='cat',
            field=models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsCat_in', to='Models.GoodsCat'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='cat',
            field=models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsCat_out', to='Models.GoodsCat'),
        ),
    ]
