# Generated by Django 2.1.4 on 2019-01-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0038_auto_20190130_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='parent_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='cat',
            field=models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.GoodsCat'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='cat',
            field=models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsCat_in', to='Models.GoodsCat'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='cat',
            field=models.ForeignKey(db_column='catId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodsCat_out', to='Models.GoodsCat'),
        ),
    ]
