# Generated by Django 2.1.4 on 2018-12-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
