# Generated by Django 2.1.4 on 2018-12-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181216_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='name',
        ),
    ]
